### ISSUE TITLE
You have Upstream and Downstream Impact in Network Output backwards

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/TributaryImpact#2]
Watch the [video](https://youtu.be/E0pvlpgolJc) in #1 and you'll see this problem. I suspect this is in around line 247 of https://github.com/Riverscapes/TributaryImpact/blob/master/TributaryImpact.py?
``` python
 rows = arcpy.da.UpdateCursor(streamNetwork, ["SHAPE@", "UStreamIP", "DStreamIP"])
```

**Comment by banderson1618** [comment]
I think there was a mix up in communication when we first implemented this feature. I interpreted "Down Stream Impact" to mean "there is an impact downstream", and likewise for the Up Stream Impact. I'm not trained in this, though, so we should go with whatever makes sense to you. I'll get them swapped around ASAP.
